select = ["ALL"]
target-version = "py311"
ignore = [
    "D101",  # Missing docstring in public class
    "D104", # Missing docstring in public package
    "D100", # Missing docstring in public module
    "ANN201", # Missing return type annotation for public function `get_db`
    "D103", # Missing docstring in public function
    "INP001", # File `X` is part of an implicit namespace package. Add an `__init__.py`.
    
]