from sqlalchemy import Boolean, String
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base
from app.utils import models


class User(Base, models.ColCreatedAt):
    __tablename__ = "users"

    username: Mapped[str] = mapped_column(String(30), nullable=False, index=True)

    # recommended email str length is 254
    email: Mapped[str] = mapped_column(String(254), nullable=False, index=True)
    hashed_pwd: Mapped[str] = mapped_column(String(), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean(), default=True)

    # `id` column will be indexed by default as it is the primary key
    """
    Here, we used init=False instead of default=None because
    `init=False` will be more accurate because id will be generated by the DB
    """
    # A003 => (builtin-attribute-shadowing)
    id: Mapped[int] = mapped_column(primary_key=True, init=False)  # noqa: A003
